// import type { Metadata } from "next";
// import localFont from "next/font/local";
// import "./globals.css";
// import Sidebar from "./components/Sidebar/Sidebar";
// import GloabalStyleProvider from "./providers/GloabalStyleProvider";
// import ContextProvider from "./providers/ContextProvider";
// import {ClerkProvider,SignInButton,SignedIn,SignedOut,UserButton} from '@clerk/nextjs';



// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <ClerkProvider>
//     <html lang="en">
//       <head>
//           <link
//             rel="stylesheet"
//             href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css"
//             integrity="sha512-z3gLpd7yknf1YoNbCzqRKc4qyor8gaKU1qmn+CShxbuBusANI9QpRohGBreCFkKxLhei6S9CQXFEbbKuqLg0DA=="
//             crossOrigin="anonymous"
//             referrerPolicy="no-referrer"
//           />
//         </head>
//       <body>
//         <ContextProvider>
//         <GloabalStyleProvider>
//           <Sidebar />
//           <div className="w-full">{children}</div>
//         </GloabalStyleProvider>
//         </ContextProvider>
//       </body>
//     </html>
//     </ClerkProvider>
//   );
// }

// before alter

import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Sidebar from "./components/Sidebar/Sidebar";
import GloabalStyleProvider from "./providers/GloabalStyleProvider";
import ContextProvider from "./providers/ContextProvider";
import {ClerkProvider,SignInButton,
  SignedIn,
  SignedOut,
  UserButton} from "@clerk/nextjs";
import {auth} from "@clerk/nextjs/server";

// Load custom fonts
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// Metadata for the app
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const {userId}=auth();
  return (
    <ClerkProvider>
      <html lang="en">
        <head>
          <link
            rel="stylesheet"
            href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css"
            integrity="sha512-z3gLpd7yknf1YoNbCzqRKc4qyor8gaKU1qmn+CShxbuBusANI9QpRohGBreCFkKxLhei6S9CQXFEbbKuqLg0DA=="
            crossOrigin="anonymous"
            referrerPolicy="no-referrer"
          />
        </head>
        <body>
          <ContextProvider>
            <GloabalStyleProvider>
              <SignedOut>
                <SignInButton />
              </SignedOut>
              <SignedIn>
                <UserButton />
                {/* You can conditionally render your Sidebar or other components here */}
              </SignedIn>
              {userId && <Sidebar />}
              <div className="w-full">{children}</div>
            </GloabalStyleProvider>
          </ContextProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}